/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.fail.client;

import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.*;

/**
 *
 * @author Абс0лютный Н0ль
 */
public class ClientWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClientWindow
     */
    public ClientWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        footer = new javax.swing.JPanel();
        inputAreaScroll = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        header = new javax.swing.JPanel();
        outputAreaScroll = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java for client");
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ExitWindow(evt);
            }
        });

        footer.setPreferredSize(new Dimension(desktopPane.getWidth(), (int)(0.2 * desktopPane.getHeight())));
        footer.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                footerResize(evt);
            }
        });

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        desktopPane.add(footer);
        footer.setBounds(0, 180, 10, 10);

        inputArea.setColumns(40);
        inputArea.setRows(20);
        inputAreaScroll.setViewportView(inputArea);

        desktopPane.add(inputAreaScroll);
        inputAreaScroll.setBounds(0, 0, 150, 80);
        inputAreaScroll.getAccessibleContext().setAccessibleParent(header);

        header.setPreferredSize(new Dimension(desktopPane.getWidth(), (int) (0.8 * desktopPane.getHeight()))
        );
        header.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                HeaderResize(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        desktopPane.add(header);
        header.setBounds(0, 0, 10, 10);

        outputArea.setColumns(40);
        outputArea.setRows(20);
        outputAreaScroll.setViewportView(outputArea);

        desktopPane.add(outputAreaScroll);
        outputAreaScroll.setBounds(280, 0, 120, 70);
        outputAreaScroll.getAccessibleContext().setAccessibleParent(header);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        CloseWindow();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void footerResize(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_footerResize
        // TODO add your handling code here:
        footer.setSize(desktopPane.getWidth(), (int) (0.2 * desktopPane.getHeight()));
        footer.setLocation(0, desktopPane.getHeight());
    }//GEN-LAST:event_footerResize

    private void ExitWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ExitWindow
        // TODO add your handling code here:
        CloseWindow();
    }//GEN-LAST:event_ExitWindow

    private void HeaderResize(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_HeaderResize
        // TODO add your handling code here:
        header.setSize(desktopPane.getWidth(), (int) (0.8 * desktopPane.getHeight()));
        inputAreaScroll.setSize((int) (0.4 * header.getWidth()), header.getHeight());
        outputAreaScroll.setSize((int) (0.4 * header.getWidth()), header.getHeight());
        outputAreaScroll.setLocation(header.getWidth() - outputAreaScroll.getWidth(), 0);
    }//GEN-LAST:event_HeaderResize

    public void CloseWindow() {
        Object[] options = {"Да", "Нет!"};
        JOptionPane.showOptionDialog(this,
                "Закрыть окно?",
                "Подтверждение",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JScrollPane inputAreaScroll;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JScrollPane outputAreaScroll;
    // End of variables declaration//GEN-END:variables

}
